name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    # Backend Tests
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Backend Dependencies
      run: |
        cd src/backend
        npm ci
    
    - name: Run Backend Tests
      run: |
        cd src/backend
        npm test
    
    # Frontend Tests
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
    
    - name: Install Dependencies
      working-directory: ./frontend
      run: npm ci
    
    - name: Lint Code
      working-directory: ./frontend
      run: npm run lint
    
    - name: TypeScript Type Check
      working-directory: ./frontend
      run: npm run typecheck
    
    - name: Build Application
      working-directory: ./frontend
      run: npm run build
      env:
        NEXT_PUBLIC_APP_ENV: production
    
    # Noir Circuit Tests
    - name: Install Noir
      run: |
        # Installe noirup. L'exécutable sera dans $HOME/.noirup/bin/noirup
        curl -L https://raw.githubusercontent.com/noir-lang/noirup/main/install | bash
        
        # Appelle noirup en utilisant son chemin complet pour installer nargo
        "$HOME/.noirup/bin/noirup" install
        "$HOME/.noirup/bin/noirup" default stable
        
        # Ajoute le répertoire de nargo ($HOME/.nargo/bin) au GITHUB_PATH 
        # pour que nargo soit disponible dans les étapes suivantes.
        echo "$HOME/.nargo/bin" >> $GITHUB_PATH
    
    - name: Verify Noir Installation
      run: nargo --version
    
    - name: Compile and Test Noir Circuits
      run: |
        cd frontend
        npm run noir:compile
        npm test
    
    # Vercel Deployment
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./frontend
      timeout-minutes: 10