# Workflow for GeoPrivacy CI/CD - tests
name: GeoPrivacy CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-and-test: # CI job for frontend linting and testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: List frontend directory content
      run: |
        echo "Listing frontend:"
        ls -la frontend || echo "frontend directory not found or ls failed"

    - name: Setup Node.js for Frontend
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: npm ci
    
    - name: Display package.json content from frontend
      working-directory: ./frontend
      run: |
        echo "--- Content of frontend/package.json (from Action runner) ---"
        cat package.json || echo "Failed to cat package.json"
        echo "---------------------------------------------------------------------"
        
    - name: List available npm scripts in frontend
      working-directory: ./frontend
      run: npm run || echo "npm run command failed"

    - name: Lint Frontend Code
      working-directory: ./frontend
      run: npm run lint
    
    - name: Run Frontend Tests
      working-directory: ./frontend
      run: npm test

    # Unit tests for frontend/backend will be added here later if needed

  deployment-check:
    needs: [lint-and-test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    
    - name: Simulate Deployment
      working-directory: ./frontend
      run: |
        npm ci
        npm run project:validate
        # Placeholder for any non-contract deployment validation

  vercel-deployment:
    needs: [deployment-check]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        # zeit-token is deprecated but kept for backward compatibility with older Vercel action versions
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./frontend
        github-comment: false

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [vercel-deployment]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  # Security job removed as it was focused on blockchain contracts
  # New security checks can be added here in the future if needed
